services:
  client:
    container_name: client
    build: './digital_twin_client/'
    ports:
      - '8383:80'
    networks:
      - digitaltwin
    depends_on:
      - server

  server:
    container_name: server
    build: './digital_twin_server/'
    ports:
      - '8080:8080'
    networks:
      - digitaltwin

networks:
  digitaltwin:
